### ISSUE TITLE
Empty set as default in defaultdict

### ISSUE THREAD

**Issue by ymer** [JuliaLang/DataStructures.jl#242] opened 2016-12-29 18:41 UTC
I'm quite sure I used to be able to do this in an earlier version:

d = DefaultDict(Set)
push!(d[0], 1)

Now it gives this error message:
LoadError: MethodError: no method matching push!(::Type{Set}, ::Int64)

**Comment by kmsquire** [comment] 2017-01-18 09:05
This works for me on Julia 0.5.  What version of Julia are you using?

**Comment by kmsquire** [comment] 2017-01-18 09:27
(And on Julia 0.6)

**Comment by ymer** [comment] 2017-01-24 13:23
I was using Julia 0.5. But I cannot recreate it now.

**Comment by kmsquire** [comment] 2017-01-24 14:50
Thanks fir checking. 

If you're concerned about performance, you should add type parameters to both the DefaultDict and the Set. 

Closing for now. Please reopen if you rediscover a way to consistently reproduce this issue. Thanks for reporting it!

**Closed by kmsquire** 2017-01-24 14:50 UTC
